print("Initializing defaults...")

DEFAULT_PLOT_WIDTH  = 16
DEFAULT_PLOT_HEIGHT =  9

DEFAULT_PLOT_WIDTH_MEDIUM  = DEFAULT_PLOT_WIDTH  * 0.75
DEFAULT_PLOT_HEIGHT_MEDIUM = DEFAULT_PLOT_HEIGHT * 0.75

DEFAULT_PLOT_WIDTH_HALF  = DEFAULT_PLOT_WIDTH  * 0.5
DEFAULT_PLOT_HEIGHT_HALF = DEFAULT_PLOT_HEIGHT * 0.5

DEFAULT_COMBINED_PLOT_WIDTH_HALF = DEFAULT_PLOT_WIDTH_HALF * 1.5

LEGEND_TEXT_SIZE         = 15
LEGEND_TEXT_SIZE_SMALLER = LEGEND_TEXT_SIZE - 2

GEO_SHOW_HS             = TRUE

GEO_PIEMAP_OPACITY      = NA   #.7 - setting the opacity to a value < 1 increases the rendering time consistently
GEO_PIEMAP_USE_CENTROID = TRUE

print("Defaults initialized!")